### PR TITLE
Unified error messages

### PR DESCRIPTION
**Pull request by alexal**
Please see issue #358

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks a lot for this!! In general I think we should still split 2 patters: `failed to read` and `failed to parse`. I will review this ASAP.

**Comment by alexal** [comment]
Thanks, I can do that. Just let me know if you think I have to split them.

**Comment by SuperQ** [comment]
Yes, we very much should have a different error for "unable to read" and "unable to parse".

**Comment by SuperQ** [comment]
It looks like this needs a rebase and to be updated with the two different error messages.

**Comment by SuperQ** [comment]
This appears abandoned.

**Pull request closed without merging**
