### PR TITLE
Add NSpid to proc status

### PR DESCRIPTION
**Pull request by NirLevy98**
This adds the NSpid to `ProcStatus`

### CODE REVIEW

**Comment by NirLevy98** [comment]
@pgier  @discordianfish

**Review by discordianfish — APPROVED** [review]

**Comment by NirLevy98** [comment]
@discordianfish 
Could you please take another look at this? In a situation where NSpid has two pids, I will take the first one.

**Comment by discordianfish** [comment]
@NirLevy98 Why taking the first one instead of exposing a list of pids?

**Comment by NirLevy98** [comment]
@discordianfish Support for a list of NSPIDs has been added

**Comment by NirLevy98** [comment]
@discordianfish is it ok now ?

**Comment by NirLevy98** [comment]
@discordianfish is it ok now ? :)

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
