### PR TITLE
Add license check

### PR DESCRIPTION
**Pull request by SuperQ**
* Add licence check script.
* Add to Makefile.
* Add to CI.
* Fix license in several files.

Closes: https://github.com/prometheus/procfs/issues/37

### CODE REVIEW

**Comment by grobie** [comment]
The year in the license header should reflect the year the file was added AFAIK.

**Comment by SuperQ** [comment]
Hmm, I thought it was usually the last modified time.

**Comment by SuperQ** [comment]
Some other opinions on the subject say it's for "When the notice is first applicable".  In this case, you might have the opinion that the notice is first applicable now, since it did not exist before.

**Comment by grobie** [comment]
Sounds fair, we should stick to this definition and not update the year of
existing license headers.

**Pull request merged**
