### PR TITLE
Hardcode USER_HZ to 100.

### PR DESCRIPTION
**Pull request by juliusv**
See comment in the file for details.

### CODE REVIEW

**Comment by juliusv** [comment]
@grobie @joshdevins @beorn7 @brian-brazil

**Comment by discordianfish** [comment]
:+1:

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
:+1: 

Want @grobie to reply, too...

**Comment by grobie** [comment]
:+1: :)

**Pull request merged**
