### PR TITLE
Add parsing numa vmstat

### PR DESCRIPTION
**Pull request by kwisniewski98**
Signed-off-by: Wisniewski, Krzysztof2 Krzysztof2.Wisniewski@intel.com

### CODE REVIEW

**Review by discordianfish — APPROVED** [review]
LGTM

**Comment by discordianfish** [comment]
Awesome, thanks!

**Comment by Creatone** [comment]
Is any possibility to merge this?

**Comment by discordianfish** [comment]
@SuperQ @pgier *bump*

**Pull request merged**
