### PR TITLE
Test on various Go OS versions.

### PR DESCRIPTION
**Pull request by SuperQ**
Setup a test matrix to make sure we avoid platform issues.

Closes: https://github.com/prometheus/procfs/issues/111

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Hmm, that doesn't seem to be taking effect

**Comment by SuperQ** [comment]
Yea, not sure why the env isn't getting used.

**Comment by SuperQ** [comment]
@brian-brazil Ok, I had to do some refactoring of the build pipeline.

**Comment by SuperQ** [comment]
@beorn7 Yea, promu is focused around building/testing binaries, not libraries. I think this works well enough for now.

**Pull request merged**
