### PR TITLE
Replace float64 with *float64 for proc_netstat, proc_snmp and proc_snmp6

### PR DESCRIPTION
**Pull request by nikakis**
This PR is related to this issue #434 which is needed for https://github.com/prometheus/node_exporter/issues/2336

Signed-off-by: Nikos Kakavas <nikakis@protonmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
It seems like your procfs branch is out of date. Also, you need to setup a global gitignore.

Use [`git config --global core.excludesFile`](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/).

**Comment by SuperQ** [comment]
Please also either link to an issue, or include a description about why you are making changes.

**Comment by nikakis** [comment]
@SuperQ Any idea about how i should proceed with the `codespell` error?

**Comment by SuperQ** [comment]
Looks like the codespell issues are unrelated. They can be ignored.

**Comment by nikakis** [comment]
> Looks like the codespell issues are unrelated. They can be ignored.

Ok, so I am waiting for an approval from your side, right?

**Review by discordianfish — APPROVED** [review]
LGTM

**Comment by nikakis** [comment]
@SuperQ Does this looks good to you? Can we merge it?

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
