### PR TITLE
feat: add LoadSysConfig method for read sys config easier #502

### PR DESCRIPTION
**Pull request by Jack-Kingdom**

### CODE REVIEW

**Review by SuperQ — CHANGES_REQUESTED** [review]
I don't see what this is useful for. It appears to be a trivial wrapper around ReadFileNoStat. This seems somewhat useless as it's just unwrapping and then re-wrapping the path string.

**Comment by Jack-Kingdom** [comment]
@SuperQ yeah, you know there is a batch of sysctl config located under procfs.
Under sysctl config file, They looks like this:
```
# enable fast open
net.ipv4.tcp_fastopen = 3
# turn on path MTU discovery
net.ipv4.tcp_mtu_probing = 1
# tcp window scaling
net.ipv4.tcp_window_scaling = 1
```

and under procfs, it's saparated files located at different path.
for example:
```
/proc/sys/net/ipv4/tcp_fastopen
```

at first, I want to provide a struct and read those config into struct. but thosed config very scattered and commonly a file only contains a single config. so I created this helper method to load those config. Is there a better way ?

**Comment by SuperQ** [comment]
Oh, you want to access sysctls. I would recommend using a dedicated package like https://github.com/lorenzosaino/go-sysctl.

**Comment by SuperQ** [comment]
I don't think we need a sysctl library here.

**Pull request closed without merging**
