### PR TITLE
Fixed ARP table MAC address parsing, added Flags field

### LINKED ISSUE #413: Incomple arp entries are returned with MAC address 30:30:3a:...
Hello,
to reproduce the bug you have to ping wide LAN range, that will create a lot of incomplete entries, and, after execution `procfs.GatherARPEntries()`, incomplete entries are returned like:
```
{192.168.0.111 30:30:3a:30:30:3a:30:30:3a:30:30:3a:30:30:3a:30:30 eth0}
{192.168.0.46 30:30:3a:30:30:3a:30:30:3a:30:30:3a:30:30:3a:30:30 eth0}
```
while arp -n reports:
```
192.168.0.111                    (incomplete)                              eth0
192.168.0.46                     (incomplete)                              eth0
```
This is not critical as all incomplete entries may be filtered by MAC address, still it might be better to return such entries with empty MAC address

### PR DESCRIPTION
**Pull request by und3f**
- Added ARPEntry.Flags field related to entry flags
- Added ARPEntry.IsComplete() to check if entry is complete
- Fixed mac address parsing and error handling
- Test improved with incomplete entry information
Closes #413.

Signed-off-by: Serhii Zasenko <sergii@zasenko.name>

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM, Thanks!

**Comment by SuperQ** [comment]
Minor cleanup of the const names, but otherwise this is great.

**Review by discordianfish — APPROVED** [review]
Good catch, thanks!

**Comment by und3f** [comment]
Glad it suits!)

**Pull request merged**
