### PR TITLE
cpuinfo: fix platform constraints

### PR DESCRIPTION
**Pull request by pgier**
Fix issues with platform constraints found by @mfraioli

### CODE REVIEW

**Comment by discordianfish** [comment]
Ugh, I wish we had a way to test this.

**Comment by mfraioli** [comment]
I have access to ppc and s390 build systems that can verify it. But since we're picking this up as a dependency of a dependency, it's hard for me to pick up a branch rather than the master. If you go ahead and merge it I can verify quickly. Since it's already broken, this at least shouldn't make it any worse.

**Comment by mfraioli** [comment]
For reference description of the issues is in #257

**Comment by mfraioli** [comment]
Thanks @pgier this built successfully on my ppc64le and s390x systems!

**Comment by discordianfish** [comment]
Yeah manual verification is one thing but maybe it's worth investing in a qemu based setup to test all supported platforms. But after spending some hours just trying to get freebsd/x86 working I kinda gave up on that.

**Pull request merged**
