### PR TITLE
add parsing of /proc/cpuinfo

### PR DESCRIPTION
**Pull request by pgier**

### CODE REVIEW

**Comment by pgier** [comment]
@SuperQ @discordianfish you guys ok with this?

**Comment by SuperQ** [comment]
Yes, this is totally in line with this code.

**Comment by pgier** [comment]
@SuperQ I initially implemented the fields of the `CPUInfo` struct using uints and floats where it seemed appropriate, however, I'm kind of wondering if it would be better to just make all the struct fields strings.  Since most or all of these would likely be used as labels and not as metric values, it seems kind of pointless to convert to a numeric type if we're just going to convert back to a string later anyway.  This would also mean we need less error checking and we can just return whatever value is read even if it's not a valid number.
WDYT?  Should all the struct fields be strings here?

**Comment by pgier** [comment]
Another possibility is to just use a `map[string]string` instead of interpreting the fields at all

**Comment by SuperQ** [comment]
I think keeping things numeric is fine, as this library can be used for other things besides node_exporter labels. :smile:

**Comment by pgier** [comment]
My concern is that we'll run into some case where cpuinfo contains a non-numeric value for one of these fields, and then it becomes a bug in procfs.  If we just return the string, then it's up to the client code to determine how to correctly interpret the data, and they can add some handling for specific weird cases if needed.

**Comment by SuperQ** [comment]
`#proc-life`

**Comment by pgier** [comment]
I'm just going to change the ID fields to strings since I think math operations on those fields normally doesn't make sense, and also change the CPU MHz to a float64 since that should always be numeric hopefully.

**Pull request merged**
