### PR TITLE
Sync golangcli-lint workflow with https://github.com/prometheus/node_exporter/blob/master/.github/workflows/golangci-lint.yml

### PR DESCRIPTION
**Pull request by conallob**
Highlights include bumping golangci-lint-action to v3.4.0, Release Notes: https://github.com/golangci/golangci-lint-action/releases/tag/v3.4.0

### CODE REVIEW

**Comment by SuperQ** [comment]
I would recommend copying the current node_exporter config wholesale.

**Comment by conallob** [comment]
> I would recommend copying the current node_exporter config wholesale.

Done. Perhaps it should be in it's own repository some day.

**Comment by SuperQ** [comment]
We used to have this script automatically synced from `prometheus/prometheus`, but the CI there was reworked and we stopped updating it. :(

**Review by SuperQ — APPROVED** [review]

**Comment by conallob** [comment]
> We used to have this script automatically synced from `prometheus/prometheus`, but the CI there was reworked and we stopped updating it. :(

Have you considered a mono repo? :P

**Comment by discordianfish** [comment]
Yeah we should have a dedicated repo for gh actions and use them in all other repos with `uses`.

**Comment by conallob** [comment]
If somebody in @prometheus can create the new repository for GitHub actions, I'm happy to make PRs to move things around

**Comment by SuperQ** [comment]
@roidelapluie Was planning to move more of the CircleCI flows to actions. Not sure where that project ended up.

**Pull request merged**
