### PR TITLE
Bug Fix: SystemCPUfreq fails when any core is offline

### PR DESCRIPTION
**Pull request by taherkk**
SystemCpufreq function does not check if a core is online before collecting metrics. In the case when a core is offline it fails and does not collect a couple of metrics.

Refer https://github.com/prometheus/node_exporter/issues/2577 for more details

### CODE REVIEW

**Comment by taherkk** [comment]
I have read the readme and steps for contribution and have tried my best to follow it. This my first open source contribution so please guide me if I have missed something.

**Comment by taherkk** [comment]
Tests are failing because each directory under .../cpu[0-9] has a file named online in Linux except for cpu0. This denotes if the core is online or not.
I added the file in my local setup manually and the tests are passing.

Please help me in configuring that file using fixtures.

**Review by pgier — APPROVED** [review]
This looks good to me in general.  I'm just wondering if there is a way to just check `/sys/devices/system/cpu/offline` which should be empty most of the time (no CPUs offline)?

**Comment by discordianfish** [comment]
You also need to sign off your commit, see the failing DCO check above

**Comment by taherkk** [comment]
Signed off my commit.
Not sure why the lint step is failing.

**Comment by discordianfish** [comment]
Here is the lint error:
```
#!/bin/bash -eo pipefail
git diff --exit-code
diff --git a/testdata/fixtures.ttar b/testdata/fixtures.ttar
index cb49947..b80316a 100644
--- a/testdata/fixtures.ttar
+++ b/testdata/fixtures.ttar
@@ -12543,11 +12543,6 @@ Mode: 444
 Directory: fixtures/sys/devices/system/cpu/cpu1
 Mode: 775
 # ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-Path: fixtures/sys/devices/system/cpu/cpu1/online
-Lines: 1
-1
-Mode: 544
-# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 Directory: fixtures/sys/devices/system/cpu/cpu1/cpufreq
 Mode: 775
 # ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -12606,6 +12601,11 @@ Lines: 1
 <unsupported>
 Mode: 664
 # ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+Path: fixtures/sys/devices/system/cpu/cpu1/online
+Lines: 1
+1
+Mode: 544
+# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 Directory: fixtures/sys/devices/system/cpu/cpu1/thermal_throttle
 Mode: 755
 # ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Exited with code exit status 1
CircleCI received exit code 1
```

You probably didn't run `make fixtures` to create the ttar file

**Comment by taherkk** [comment]
I'm exploring checking for offline cpu's in `/sys/devices/system/cpu/offline`

Just sharing the approach here:
Get cpu's from the file.
Expand ranges.
Filter cpu's which not physically present (Though I have a hexacore CPU the offline file shows a range of 12-15 which are not physically present)
In the for loop add an isOnline check which uses binary search on the slice of offline cpu's.

**Comment by taherkk** [comment]
@pgier, I have updated the code according to the approach mentioned earlier.

**Review by discordianfish — APPROVED** [review]
Thanks!

**Comment by taherkk** [comment]
raised a PR for it @pgier

**Pull request merged**
