### PR TITLE
IPVS: Add support for parsing FWM virtual servers

### PR DESCRIPTION
**Pull request by madddi**

### CODE REVIEW

**Comment by SuperQ** [comment]
Can you add a sample to the [fixture](https://github.com/prometheus/node_exporter/blob/master/collector/fixtures/proc/net/ip_vs)

**Comment by madddi** [comment]
@SuperQ Sorry, done. This brought up a bug, which i fixed. Maybe have a look at it as I'm not super happy with the way I fixed it but can't find a better way.

**Comment by SuperQ** [comment]
The fix looks right to me.  Maybe @grobie can comment on it.

**Comment by grobie** [comment]
Fixed with d098ca1 in master (I had to rebase manually).

**Comment by SuperQ** [comment]
Thanks @grobie!

**Pull request closed without merging**
