### PR TITLE
Add notice about library stability.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@grobie See https://github.com/prometheus/procfs/pull/8

**Comment by grobie** [comment]
I don't see why it should be limited to prometheus use. :+1: to add a note that this project is work in progress and that the public interface might change in backwards incompatible ways without warnings though.

**Comment by juliusv** [comment]
@grobie updated the wording

**Comment by GeertJohan** [comment]
:+1: good move

**Pull request merged**
