### PR TITLE
Package fixtures directory using ttar

### LINKED ISSUE #78: Support binary files in ttar
The procfs file structure is not compatible with non-Linux systems. For example symlinks cause issues when checked out on Windows or Mac (see #60 and #75). For similar reasons, a `ttar` solution was contributed which allows packaging the whole fixtures structure into a single file, while still allowing meaningful diffs and code reviews.

In order to use `ttar` for the `fixtures/` directory, it needs to support encodeing+decoding null bytes so that files like `cmdline` can be packaged as well.

@ideaship @SuperQ

### PR DESCRIPTION
**Pull request by grobie**
@ideaship @brian-brazil @SuperQ 

Fixes #78 #75 #60

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by ideaship** [comment]
@grobie @brian-brazil Wow, you guys are quick. The patch was merged before I could check it out. I am not enthusiastic about this patch: it turns two strings (at least one of which is rather common in all kinds of files) into magic keywords that must not be part of the input files or ttar will break. How much are you willing to bet that "EOF" will never, ever turn up in any file that you would like to put into fixtures?

A longer code string (e.g., "EOF-gaev9AeKiv") would IMO be much less problematic. Maybe we could even work out a solution with escaping which would cover all possible files. Would you be willing to consider an improved patch? I could at least look into it.

**Comment by grobie** [comment]
@ideaship Thanks for still looking into this! I'd be more than happy to accept improved solutions to this issue.

I was considering the possible clashes on EOF, but given we control the content of the fixture files here, came to the conclusion that it's good enough for now. For a general purpose ttar implementation, I can see issues with that though. My main goal was to provide a solution the reported issues with symlinks and exe files in this repo.

I could imagine that we could avoid the EOF marker at all and mark missing line endings different somehow. One thing to keep in mind with the keywords is that the created ttar file should remain human readable, so we shouldn't go too crazy I guess.

Again, thanks a ton for your continued contributions! We use ttar in https://github.com/prometheus/node_exporter as well by now. You should consider creating a repo for it so you can become famous ;-)

**Comment by grobie** [comment]
Oh, and after sending the last comment I checked your profile and you already did that! I created #81 to eventually vendor ttar from your repo which should become the canonical source.

**Comment by ideaship** [comment]
Cool. I already imported your fix, but I could not get myself to push it because I hope I can come up with a better solution, now that I know there is a need. By the way, I just noticed that the "wc -l | cut" part appears to need tweaking to work on macOS.

**Comment by grobie** [comment]
Ah, dang. I usually try to avoid awk if not necessary. Feel free to revert
that as it seems to be more portable.

**Comment by ideaship** [comment]
I'll take a look. Give me a couple of days or so.

**Comment by ideaship** [comment]
@grobie I posted an update to https://github.com/ideaship/ttar.

**Pull request merged**
